In [2]:
import numpy as np

In [12]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [14]:
arr?

Type:        ndarray
String form: [1 2 3 4 5]
Length:      5
File:        c:\users\lecia\anaconda3\envs\data_analysis\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optiona

In [25]:
zeros = np.zeros((3,3))
print(zeros.ndim)
print(zeros.shape)
print(zeros.size)
print(zeros.dtype)

2
(3, 3)
9
float64


In [32]:
arr[1:5] = 23,23,23,23
arr

array([100,  23,  23,  23,  23])

In [6]:
x = np.array([[1,2,3,4],[5,6,7,8]])
y = np.array([[0,2],[1,2],[1,2],[2,2]])
z = np.dot(x,y)
z

array([[13, 20],
       [29, 52]])

In [7]:
np.sin(z)

array([[ 0.42016704,  0.91294525],
       [-0.66363388,  0.98662759]])